version: '3.8'

services:
  juice-shop-eg:
    image: node:20
    container_name: juice-shop-eg
    ports:
      - "4200:4200"
      - "3000:3000"
    volumes:
      - ./app:/app
    working_dir: /app
    environment:
      NODE_ENV: development
    command: "bash -c 'npm i && npm i @angular/cli && npm run serve:dev'"
    restart: unless-stopped
